🧠 Matrix Operations Challenge

# Objective

Implement a 2D `Matrix` class in Python that supports:

- Basic arithmetic operations (`+`, `-`, `*`, `@`, `**`)
- Broadcasting
- Complex expressions
- Performance optimization using tools like:
  - `__slots__`
  - Memory footprint analysis
  - Profiling (`cProfile`, `line_profiler`)
  - Optional: Rewriting parts in **Cython**

You will be graded on correctness, efficiency, profiling output, and how well you optimize the implementation.


## ✅ Task 1: Implement All Methods

Complete the following special methods in the `Matrix` class:

| Method       | Operation             | Description                        |
|--------------|------------------------|------------------------------------|
| `__add__`    | `A + B`                | Supports broadcasting              |
| `__sub__`    | `A - B`                | Supports broadcasting              |
| `__mul__`    | `A * B`                | Element-wise multiplication        |
| `__matmul__` | `A @ B`                | Matrix multiplication              |
| `__pow__`    | `A ** n`               | Element-wise exponentiation        |


In [4]:
#skeleton
import numpy as np

class Matrix:
    """
    A 2D Matrix class supporting basic operations and broadcasting.
    Internally uses NumPy for performance but encapsulates it for educational purposes.
    """
    __slots__ = ['data']  # Optimization: Reduces memory overhead

    def __init__(self, data):
        if isinstance(data, list):
            data = np.array(data)
        if not isinstance(data, np.ndarray):
            raise TypeError("Data must be a list or NumPy array")
        if data.ndim == 1:
            data = data[np.newaxis, :]  # Allow row vector broadcasting
        elif data.ndim != 2:
            raise ValueError("Only 2D matrices are allowed")
        self.data = data

    def __add__(self, other):
        other_data = other.data if isinstance(other, Matrix) else other
        return Matrix(self.data + other_data)

    def __sub__(self, other):
        other_data = other.data if isinstance(other, Matrix) else other
        return Matrix(self.data - other_data)

    def __mul__(self, other):
        other_data = other.data if isinstance(other, Matrix) else other
        return Matrix(self.data * other_data)

    def __matmul__(self, other):
        other_data = other.data if isinstance(other, Matrix) else other
        return Matrix(self.data @ other_data)

    def __pow__(self, power):
        return Matrix(self.data ** power)

    def __str__(self):
        return str(self.data)

    def __repr__(self):
        return f"Matrix({repr(self.data)})"

    def shape(self):
        return self.data.shape






In [6]:
### 🧪 Task 2: Demonstrate a Complex Expression

#result = (A + B) @ (A - B) ** 2

# Create matrices
A = Matrix([[1, 2],
            [3, 4]])

B = Matrix([5, 6])  

result = (A + B) @ (A - B) ** 2

# Print results
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Result of (A + B) @ (A - B) ** 2:\n", result)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]]
Result of (A + B) @ (A - B) ** 2:
 [[128 128]
 [168 168]]


In [7]:
### ⏱️ Task 3: Time Execution

import time

# Initialize A and B again for timing context
A = Matrix([[1, 2], [3, 4]])
B = Matrix([5, 6])

# Run multiple times for averaging
runs = 10000
start = time.perf_counter()

for _ in range(runs):
    result = (A + B) @ (A - B) ** 2

end = time.perf_counter()

avg_time = (end - start) / runs
print(f"Average execution time over {runs} runs: {avg_time:.8f} seconds")


Average execution time over 10000 runs: 0.00002244 seconds


In [8]:
### 🧯 Task 4: Measure Memory Footprint

import tracemalloc

# Start memory tracking
tracemalloc.start()

# Initial memory snapshot
start_snapshot = tracemalloc.take_snapshot()

# Run the complex expression
result = (A + B) @ (A - B) ** 2

# Final memory snapshot
end_snapshot = tracemalloc.take_snapshot()

# Compare memory usage
stats = end_snapshot.compare_to(start_snapshot, 'lineno')

print("\n[Memory Usage Differences]")
for stat in stats[:5]:  # top 5 lines
    print(stat)


[Memory Usage Differences]
c:\Python311\Lib\tracemalloc.py:560: size=320 B (+320 B), count=2 (+2), average=160 B
c:\Python311\Lib\tracemalloc.py:423: size=320 B (+320 B), count=2 (+2), average=160 B
C:\Users\tanis\AppData\Local\Temp\ipykernel_8676\3414285132.py:36: size=152 B (+152 B), count=3 (+3), average=51 B
c:\Python311\Lib\codeop.py:125: size=341 B (+48 B), count=3 (+1), average=114 B
c:\Python311\Lib\tracemalloc.py:313: size=48 B (+48 B), count=1 (+1), average=48 B


In [9]:
### 📊 Task 5: Profile Function Calls

import cProfile

def compute_expression():
    A = Matrix([[1, 2], [3, 4]])
    B = Matrix([5, 6])
    return (A + B) @ (A - B) ** 2

# Profile it
print("\n[cProfile Output]")
cProfile.run('compute_expression()')


[cProfile Output]
         31 function calls in 0.001 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.000    0.000 3028594434.py:5(compute_expression)
        6    0.000    0.000    0.000    0.000 3414285132.py:11(__init__)
        1    0.000    0.000    0.000    0.000 3414285132.py:22(__add__)
        1    0.000    0.000    0.000    0.000 3414285132.py:26(__sub__)
        1    0.000    0.000    0.000    0.000 3414285132.py:34(__matmul__)
        1    0.000    0.000    0.000    0.000 3414285132.py:38(__pow__)
        1    0.000    0.000    0.000    0.000 <string>:1(<module>)
        1    0.000    0.000    0.001    0.001 {built-in method builtins.exec}
       15    0.000    0.000    0.000    0.000 {built-in method builtins.isinstance}
        2    0.000    0.000    0.000    0.000 {built-in method numpy.array}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profile

In [ ]:
### 🔍 Task 6: Line-by-Line Profiling

%pip install line_profiler

@profile
def __add__(self, other):
    return Matrix(self.data + self._get_data(other))

# Run th Command-  # kernprof -l -v matrix_challenge.py 
# by keeping the code above in a separate matrix_challenge.py file

In [11]:
### 🚀 Task 7: Optimize!

import numpy as np

class Matrix:
    """
    A 2D Matrix class supporting basic operations and broadcasting.
    Optimized with __slots__ to reduce memory usage.
    """

    __slots__ = ['data']  # ⏱️ optimization: saves per-instance memory

    def __init__(self, data):
        if isinstance(data, list):
            data = np.array(data)
        if not isinstance(data, np.ndarray):
            raise TypeError("Data must be a list or NumPy array")
        if data.ndim == 1:
            data = np.expand_dims(data, axis=0)  # broadcast 1D to 2D row vector
        elif data.ndim != 2:
            raise ValueError("Only 2D matrices are allowed")
        self.data = data

    def _get_data(self, other):
        return other.data if isinstance(other, Matrix) else other

    def __add__(self, other):
        return Matrix(self.data + self._get_data(other))

    def __sub__(self, other):
        return Matrix(self.data - self._get_data(other))

    def __mul__(self, other):
        return Matrix(self.data * self._get_data(other))

    def __matmul__(self, other):
        return Matrix(self.data @ self._get_data(other))

    def __pow__(self, power):
        return Matrix(self.data ** power)

    def __str__(self):
        return str(self.data)

    def __repr__(self):
        return f"Matrix({repr(self.data)})"

    def shape(self):
        return self.data.shape